# Generated by Django 4.2.4 on 2023-10-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appfinal', '0004_alter_estilos_descripcion_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='estilos',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
