# Generated by Django 4.2.4 on 2023-10-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appfinal', '0006_remove_estilos_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResenaCerveza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('cerveceria', models.CharField(max_length=100)),
                ('estilo', models.CharField(max_length=50)),
                ('contenido', models.TextField()),
                ('calificacion', models.FloatField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
