# Generated by Django 4.2.4 on 2023-10-20 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appfinal', '0010_remove_resenacerveza_creado_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientes',
            name='estilo',
        ),
    ]
