# Generated by Django 4.2.4 on 2023-10-22 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appfinal', '0014_like_mensaje_likes_alter_ingredientes_descripcion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
